apiVersion: v1
kind: Pod
metadata:
  name: mobilebackend
  namespace: waziup
  labels:
    name: mobilebackend
spec:
  containers:
  - name: mobilebackend
    image: waziup/mobilebackend
    ports:
    - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: mobilebackend
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31330
  selector:
    name: mobilebackend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mobilebackend
  namespace: waziup
spec:
  rules:
  - host: mobilebackend.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: mobilebackend
          servicePort: 3000

