sudo: required

language: nodejs

services:
- docker

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:
- docker-compose build
- mkdir -p data/mongo data/keycloak/content data/els
- chmod -R 777 data

script:
- docker-compose up & 
- sleep 60
- ./tests/platform_tests.sh

after_script:
- docker-compose down
