version: '3'

# This file complements the original docker-compose.yml by adding Mongo DB auth configuration (login and password).
# Usage: docker-compose -f docker-compose.yml -f docker-compose-dbauth.yml up

services:
# Broker
  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS

  orion:
    entrypoint: ["sh", "-c", "rm /tmp/contextBroker.pid; /usr/bin/contextBroker -fg -multiservice -dbhost mongo -dbuser $MONGODB_USER -dbpwd $MONGODB_PASS -logLevel DEBUG"]

  waziup-api:
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
