version: '2'

services:

# Broker
  mongo:
    image: mongo:3.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${WAZIUP_DATA}/mongo:/data/db'

  orion:
    image: fiware/orion:1.7.0
    hostname: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel INFO
    network_mode: host
    extra_hosts:
      - "mongo:127.0.0.1"
      - "localhost:127.0.0.1"

  api-server:
    build: ./api-server
    image: waziup/api-server:1.0
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - KEYCLOAK_URL=http://${WAZIUP_URL}:8080/auth
      - ORION_URL=http://orion:1026
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_URL=mongodb://mongo:27017/waziup_history
      - SOCIALS_URL=http://socials:9123
      - LOG_LEVEL=debug
    network_mode: host
    extra_hosts:
      - "orion:127.0.0.1"
      - "elasticsearch:127.0.0.1"
      - "mongo:127.0.0.1"
      - "socials:127.0.0.1"

# Users identification & authorization   
  keycloak:
    build: ./keycloak
    image: waziup/keycloak:1.0
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=mysql
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${WAZIUP_ADMIN_PASS}
      - KEYCLOAK_LOGLEVEL=DEBUG
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
    volumes:
      - ${WAZIUP_DATA}/keycloak:/opt/jboss/keycloak/standalone/data/
    # If the realm "waziup" doesn't exists, create it from file
    entrypoint: "/opt/jboss/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.dir=/opt/jboss/keycloak/imports"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${WAZIUP_DATA}/mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

# Dashboard    
  dashboard:
    build: ./dashboard
    image: waziup/dashboard:1.0
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - KEYCLOAK_URL=http://${WAZIUP_URL}:8080/auth
      - API_SERVER_URL=http://${WAZIUP_URL}/api
    mem_limit: 1000000000  

#Socials
  socials:
    build: ./socials
    image: waziup/socials:1.0
    ports:
      - 9123:9123
    environment:
      - MONGODB_URL=mongodb://localhost:27017/waziup_socials
    links:
      - mongo

# ELS
  elasticsearch:
    build: ./elasticsearch
    image: waziup/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    mem_limit: 1500000000  
    volumes:
      - ${WAZIUP_DATA}/els:/usr/share/elasticsearch/data

  kibana:
    build: ./kibana
    image: waziup/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://api-server:80/api/v1/history

  kibana-backend:
    build: kibana-backend/
    image: waziup/kibana-backend
    ports:
      - "6565:6565"
      - "5602:5602"
    environment:
      - SERVER_PORT=6565
      - ELSPROXY_PORT=9201 
      - SERVER_URL=http://localhost:6565
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KIBANA_URL=http://kibana:5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  els-feeder:
    build: ./els-feeder
    image: waziup/els-feeder
    ports:
      - "9100:9100"
    depends_on:
      - elasticsearch
      - orion
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PREFIX=waziup
      - ORION_URL=http://orion:1026
      - SERVER_PORT=9100
      - FEEDER_NAME=http://els-feeder

# CEP
#  cepheus:
#    image: orangeopensource/fiware-cepheus
#    build: ./broker/cepheus
#    hostname: cepheus
#    ports:
#      - "8080:8080"
#    links:
#      - orion
#    entrypoint: java -jar /opt/cepheus/cepheus-cep.jar -Dserver.port=7512
