version: '2'

services:

# Broker
  mongo:
    image: waziup/mongodb:latest
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${WAZIUP_DATA}/mongo:/data/db'

  orion:
    image: waziup/orion:latest
    hostname: orion
    container_name: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel INFO
    links:
      - mongo

# Front-end proxy
  proxy:
    build: ./proxy
    image: waziup/proxy:latest
    ports:
      - "80:80"
      - "443:443"

  api-server:
    build: ./api-server
    image: waziup/api-server
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=80
      - SERVER_URL=http://localhost:80
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - ORION_URL=http://orion:1026
      - ELASTICSEARCH_URL=http://elasticsearch:9200

# Users identification    
  keycloak:
    build: ./keycloak
    image: waziup/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${WAZIUP_ADMIN_PASS}
      - KEYCLOAK_LOGLEVEL=DEBUG
    volumes:
      - ${WAZIUP_DATA}/keycloak:/opt/jboss/keycloak/standalone/data/
    # If the realm "waziup" doesn't exists, create it from file
    entrypoint: "/opt/jboss/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.file=/opt/jboss/keycloak/waziup-realm.json"

# Dashboard    
  dashboard:
    build: ./dashboard
    image: waziup/dashboard:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ADMIN_USER=admin
      - REACT_APP_ADMIN_PASS=${WAZIUP_ADMIN_PASS}
      - REACT_APP_KC_URL=http://${WAZIUP_URL}:8080/auth
      - REACT_APP_ORION_API=http://${WAZIUP_URL}/api/v1/orion
      - REACT_APP_COMET_API=http://${WAZIUP_URL}/api/v1/comet
      - REACT_APP_KIBANA_URL=http://${WAZIUP_URL}:5601
    mem_limit: 1000000000  

#Socials
  socials:
    build: ./socials
    image: waziup/socials:latest
    ports:
      - 9123:9123
    environment:
      - MONGODB_URL=mongodb://localhost:27017/waziup_socials
    links:
      - mongo

# ELS
  elasticsearch:
    build: ELK/elasticsearch/
    image: waziup/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    mem_limit: 1500000000  
    volumes:
      - ${WAZIUP_DATA}/els:/usr/share/elasticsearch/data

#  logstash:
#    build: ELK/logstash/
#    image: waziup/logstash
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch
#    environment:
#      ELASTIC_SEARCH_API: "http://elasticsearch:9200"
#      ORION_API: "http://orion:1026"
#  kibana:
#    build: ELK/kibana/
#    image: waziup/kibana
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
  els-feeder:
    build: ELS-feeder/
    image: waziup/els-feeder
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - orion
    environment:
      ELASTIC_SEARCH_API: "http://elasticsearch"
      ORION_API: "http://orion:1026"

# CEP
  cepheus:
    image: orangeopensource/fiware-cepheus
#    build: ./broker/cepheus
    hostname: cepheus
    ports:
      - "8080:8080"
    links:
      - orion
#    entrypoint: java -jar /opt/cepheus/cepheus-cep.jar -Dserver.port=7512
