version: '3'

services:
# Broker
  mongo:
    image: mongo:3.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${WAZIUP_DATA}/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"

  orion:
    image: fiware/orion:2.0.0
    hostname: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG 
    network_mode: host
    extra_hosts:
      - "mongo:127.0.0.1"
      - "localhost:127.0.0.1"
    depends_on:
      - "mongo"

  servant:
    #build: ./servant
    image: waziup/servant
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_URL=http://localhost:8080/auth
      - ORION_URL=http://orion:1026
      - MONGODB_URL=mongodb://mongo:27017/waziup_history
      - LOG_LEVEL=debug
    network_mode: host
    extra_hosts:
      - "orion:127.0.0.1"
      - "elasticsearch:127.0.0.1"
      - "mongo:127.0.0.1"
      - "socials:127.0.0.1"
    depends_on:
      - orion
      - keycloak

# Users identification & authorization   
  keycloak:
    build: ./keycloak
    image: waziup/keycloak:1.1
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=mysql
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${WAZIUP_ADMIN_PASS}
      - KEYCLOAK_LOGLEVEL=DEBUG
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
    volumes:
      - ${WAZIUP_DATA}/keycloak:/opt/jboss/keycloak/standalone/data/
    # If the realm "waziup" doesn't exists, create it from file
    entrypoint: "/opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.dir=/opt/jboss/keycloak/imports"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${WAZIUP_DATA}/mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

# Dashboard    
  dashboard:
    # Specific images should be built for each environment (local, staging, production).
    image: waziup/dashboard:1.1.1-localhost
    build:
      context: ./dashboard
      args:
        - SERVER_PORT=3000
        - SERVER_URL=http://localhost:3000
        - KEYCLOAK_URL=http://localhost:8080/auth
        - API_SERVER_URL=http://localhost:800/api
    ports:
      - "3000:3000"

#Socials
  socials:
    build: ./socials
    image: waziup/socials:1.1
    ports:
      - 9123:9123
    environment:
      - MONGODB_URL=mongodb://localhost:27017/waziup_socials
    depends_on:
      - mongo