version: '2.1'

services:

# Broker
  mongo:
    image: mongo:3.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${WAZIUP_DATA}/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"

  orion:
    image: fiware/orion:1.15.0
    hostname: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel WARN 
    network_mode: host
    extra_hosts:
      - "mongo:127.0.0.1"
      - "localhost:127.0.0.1"
    depends_on:
      mongo:
        condition: service_healthy 

  api-server:
    build: ./api-server
    image: waziup/api-server:1.1.cr2
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=800
      - HTTPS_PORT=443
      - KEYCLOAK_URL=http://${WAZIUP_URL}:8080/auth
      - ORION_URL=http://orion:1026
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_URL=mongodb://mongo:27017/waziup_history
      - SOCIALS_URL=http://socials:9123
      - LOG_LEVEL=debug
    network_mode: host
    extra_hosts:
      - "orion:127.0.0.1"
      - "elasticsearch:127.0.0.1"
      - "mongo:127.0.0.1"
      - "socials:127.0.0.1"
    depends_on:
      - orion
      - keycloak
      - socials

# Users identification & authorization   
  keycloak:
    build: ./keycloak
    image: waziup/keycloak:1.1.cr2
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=mysql
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${WAZIUP_ADMIN_PASS}
      - KEYCLOAK_LOGLEVEL=DEBUG
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
    volumes:
      - ${WAZIUP_DATA}/keycloak:/opt/jboss/keycloak/standalone/data/
    # If the realm "waziup" doesn't exists, create it from file
    entrypoint: "/opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.dir=/opt/jboss/keycloak/imports"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${WAZIUP_DATA}/mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

# Dashboard    
  dashboard:
    build: ./dashboard
    # As a front-end app, specific images should be generated for each environment (local, staging, production).
    image: waziup/dashboard:1.1.cr2-${WAZIUP_URL}
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - KEYCLOAK_URL=http://${WAZIUP_URL}:8080/auth
      - API_SERVER_URL=http://${WAZIUP_URL}/api

#Socials
  socials:
    build: ./socials
    image: waziup/socials:1.1.cr2
    ports:
      - 9123:9123
    environment:
      - MONGODB_URL=mongodb://localhost:27017/waziup_socials
    links:
      - mongo

