version: '2'
services:
 waziupbroker:
    container_name: "waziupbroker"
    image: waziup/broker
    build: ./broker/kafka
    ports:
      - 9092:9092
      - 2181:2181
      - 9000:9000

 waziupmongodb:
    container_name: "waziupmongodb"
    image: waziup/database
    build: ./database
    ports:
      - 27017:27017
      - 28017:28017

 waziupwildfly:
    container_name: "waziupwildfly"
    image: pandaconstantin/waziupwildfly
    #build: ./exec_env/wildfly
    depends_on:
      - waziupmongodb
    environment:
      - MONGODB_URI=waziupmongodb
    ports:
      - 8088:8088
      - 9990:9990

 orion:
   image: fiware/orion
   links:
     - waziupmongodb
   ports:
     - "1026:1026"
   command: -dbhost waziupmongodb
