apiVersion: v1
kind: Pod
metadata:
  name: smsapp
  namespace: waziup
  labels:
    name: smsapp
spec:
  containers:
  - name: smsapp
    image: waziup/smsapp
    ports:
    - containerPort: 8000
    env:
      - name: APP_ENV
        value: local
      - name: APP_DEBUG
        value: 'true'
      - name: APP_KEY
        value: SomeRandomKey!!! 
      - name: DB_CONNECTION
        value: mysql 
      - name: DB_HOST
        value: smsdb
      - name: DB_DATABASE
        value: lumen 
      - name: DB_USERNAME
        value: lumen 
      - name: DP_PASSWORD
        value: secret 
      - name: MEMCACHED_HOST
        value: smscache
      - name: CACHE_DRIVER 
        value: memcached

---
apiVersion: v1
kind: Service
metadata:
  name: smsapp 
  namespace: waziup
spec:
  ports:
    - port: 8000
  selector:
    name: smsapp

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smsapp
  namespace: waziup
spec:
  rules:
  - host: sms2.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: smsapp
          servicePort: 8000

