apiVersion: v1
kind: Pod
metadata:
  name: smscache
  namespace: waziup
  labels:
    name: smscache
spec:
  containers:
  - name: smscache 
    image: memcached
    ports:
    - containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: smscache
  namespace: waziup
spec:
  ports:
    - port: 11211
  selector:
    name: smscache

