apiVersion: v1
kind: ReplicationController
metadata:
  name: cygnus
  namespace: waziup
  labels:
    name: cygnus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cygnus
    spec:
      containers:
      - name: cygnus
        image: waziup/cygnus:latest
        ports:
        - containerPort: 8081
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: cygnus
  namespace: waziup
spec:
  type: NodePort
  selector:
    name: cygnus
  ports:
    - name: cygnus
      port: 5050
      nodePort: 30550

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cygnus
  namespace: waziup
spec:
  rules:
  - host: cygnus.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cygnus
          servicePort: 5050
