
smsapp:
  #image: waziup/smsapp
  build: images/smsapp
  command: sh -c "php ../artisan migrate;php ../artisan serve; php-fpm"
  links:
    - smsdb
    - smscache
  ports:
    - "80:80"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: smsdb
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
    MEMCACHED_HOST: smscache
    CACHE_DRIVER: memcached
smsdb:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
smscache:
  image: memcached
