apiVersion: v1
kind: ReplicationController
metadata:
  name: sth-comet
  namespace: waziup
  labels:
    name: sth-comet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sth-comet
    spec:
      containers:
      - name: sth-comet
        image: waziup/sth-comet:latest
        ports:
        - containerPort: 8666
        env:
        - name: STH_HOST
          value: "0.0.0.0"
        - name: DB_URI
          value: "mongo:27017"

---
apiVersion: v1
kind: Service
metadata:
  name: sth-comet
  namespace: waziup
spec:
  type: NodePort
  selector:
    name: sth-comet
  ports:
    - name: sth-comet
      port: 8666
      nodePort: 30666

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sth-comet
  namespace: waziup
spec:
  rules:
  - host: brokerhistory.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: sth-comet
          servicePort: 8666
