apiVersion: v1
kind: ReplicationController
metadata:
  name: proxy
  namespace: waziup
  labels:
    name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy
    spec:
      containers:
      - name: proxy
        image: waziup/proxy:PROXY_FIX
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: waziup
spec:
  type: NodePort
  selector:
    name: proxy
  ports:
    - name: proxy
      port: 80
      nodePort: 30979

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: waziup
spec:
  rules:
  - host: orion.waziup.io
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 80
  - host: app.waziup.io
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 80
  - host: sms.waziup.io
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 80
  - host: historicaldata.waziup.io
    http:
      paths:
      - backend:
          serviceName: proxy
          servicePort: 80
