swagger: '2.0'
info:
  version: '1.0'
  title: 'WAZIUP API'
host: waziup.io

# Data structure definitions:
definitions:
  $ref: 'definitions.yaml'

tags: 
  - name: apps
    description: Applications API
  - name: data
    description: data management API
  - name: gateways
    description: gateway management API

paths:
# Apps API
  /apps/{id}:
    $ref: 'paths/apps_id.yaml'
  /apps:
    $ref: 'paths/apps.yaml'
  /apps/{id}/containers:
    $ref: 'paths/apps_id_containers.yaml'

# Data API
  /data/observations:
    $ref: 'paths/data_observations.yaml'
  /data/observations/{id}:
    $ref: 'paths/data_observations_id.yaml'
  /data/subscriptions:
    $ref: 'paths/data_subscriptions.yaml'
  /data/subscriptions/{id}:
    $ref: 'paths/data_subscriptions_id.yaml'

#Gateways API
  /gateways:
    $ref: 'paths/gateways.yaml'
  /gateways/{id}:
    $ref: 'paths/gateways_id.yaml'
  /gateways/{id}/devices:
    $ref: 'paths/gateways_id_devices.yaml'
