apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: waziup-test
  labels:
    component: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
    nodePort: 30920
  - name: transport
    port: 9300
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: waziup-test
spec:
  rules:
  - host: elasticsearch.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200

