apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: waziup-test
  labels:
    k8s-app: kibana
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kibana
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kibana
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kibana
        image: gcr.io/google_containers/kibana:v4.6.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://217.77.95.64:30920"
        #            value: "http://elasticsearch.waziup.io"
        ports:
        - containerPort: 5601
          name: ui
