apiVersion: v1
kind: Pod
metadata:
  name: broker
  namespace: waziup
  labels:
    name: broker
spec:
  containers:
  - name: mongo
    image: waziup/mongodb:latest
    args: ["--nojournal"]
    ports:
    - containerPort: 27017
    - containerPort: 28017

  - name: orion
    image: waziup/orion:latest
    ports:
    - containerPort: 1026
    args: ["-dbhost", "localhost:27017", "-logLevel", "INFO"]

  - name: cygnus
    image: waziup/cygnus:latest
    ports:
    - containerPort: 8081
    - containerPort: 5050

----
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 1026
      nodePort: 30026
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: broker

----
apiVersion: v1
kind: Service
metadata:
  name: brokerdb
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30017
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: broker

----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: broker
  namespace: waziup
spec:
  rules:
  - host: broker.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: broker
          servicePort: 1026

