version: '2'

services:
  mongo:
    image: mongo:latest
    command: --nojournal
    ports:
      - "27017:27017"
  
  orion:
    image: waziup/orion:latest
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel INFO
    links:
      - mongo
  
  cygnus:
    image: waziup/cygnus:latest
    links:
      - orion
      - mongo
    ports:
      - "8081:8081"
      - "5050:5050"
