version: '2'

services:

  mongo:
    image: waziup/mongodb:latest
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: --nojournal

  orion:
    image: waziup/orion:latest
    hostname: orion
    container_name: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo

  cygnus:
    image: waziup/cygnus
    hostname: cygnus
    container_name: cygnus
    links:
      - orion
      - mongo
    expose:
      - "5050"
    ports:
      - "5050:5050"

  sth-comet:
    image: waziup/sth-comet:latest
    hostname: sth-comet
    container_name: sth-comet
    links:
      - mongo
    ports:
      - "8666:8666"
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=mongo:27017
