apiVersion: v1
kind: ReplicationController
metadata:
  name: aam
  namespace: waziup
spec:
  replicas: 1 
  selector:
    app: aam
  template:
    metadata:
      name: aam
      labels:
        app: aam
    spec:
      containers:
      - name: aam
        image: jboss/keycloak
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_USER 
          value: "admin"
        - name: KEYCLOAK_PASSWORD 
          value: "KCadminW"
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: vol
      volumes:
      - name: vol
        hostPath:
          path: /mnt/vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: aam
  name: aam
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31083
  selector:
    app: aam

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aam
  namespace: waziup
spec:
  rules:
  - host: aam.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: aam
          servicePort: 8080
