apiVersion: v1
kind: ReplicationController
metadata:
  name: controller-proxy
  namespace: waziup
spec:
  replicas: 1 
  selector:
    app: controller-proxy
  template:
    metadata:
      name: controller-proxy
      labels:
        app: controller-proxy
    spec:
      containers:
      - name: controller-proxy
        image: waziup/controller-proxy
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: controller-proxy
  name: controller-proxy
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31082
  selector:
    app: controller-proxy

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: controller-proxy
  namespace: waziup
spec:
  rules:
  - host: api.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: controller-proxy
          servicePort: 80

