apiVersion: v1
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
  namespace: waziup
spec:
  containers:
  - name: mongo
    image: waziup/controller:latest
    ports:
    - containerPort: 8080

----
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30880
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: controller

