apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: waziup
  labels:
    name: controller
spec:
  containers:
  - name: controller
    image: waziup/controller
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31333
  selector:
    name: controller

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: controller
  namespace: waziup
spec:
  rules:
  - host: controller.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: controller
          servicePort: 8080

