apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: contrib-nginx-ingress
  labels:
    app: contrib-nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30999
    protocol: TCP
    name: http
  - port: 443
    nodePort: 31999
    protocol: TCP
    name: https
  selector:
    app: contrib-nginx-ingress

